server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}
  forward-headers-strategy: framework

app:
  secret: ${APP_SECRET}
  jwt:
    token:
      expires-in: ${APP_JWT_TOKEN_EXPIRES_IN}
    refresh-token:
      expires-in: ${APP_JWT_REFRESH_TOKEN_EXPIRES_IN}
    remember-me:
      expires-in: ${APP_JWT_REMEMBER_ME_EXPIRES_IN}
  registration:
    email:
      token:
        expires-in: ${APP_REGISTRATION_EMAIL_TOKEN_EXPIRES_IN}
    password:
      token:
        expires-in: ${APP_REGISTRATION_PASSWORD_TOKEN_EXPIRES_IN}
  default-locale: ${APP_DEFAULT_LOCALE}
  default-timezone: ${APP_DEFAULT_TIMEZONE}
  url: ${APP_URL}
  frontend-url: ${APP_FRONTEND_URL}

spring:
  application:
    name: ${APP_NAME}
    description: ${APP_DESCRIPTION}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  data:
    redis:
      database: ${REDIS_DATABASE}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}
    web:
      pageable:
        default-page-size: ${PAGEABLE_DEFAULT_PAGE_SIZE}
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
  messages:
    basename: locales.messages
    encoding: UTF-8
    cache-duration: ${MESSAGES_CACHE_DURATION}
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: ${MAIL_SSL}
          tls:
            enable: ${MAIL_TLS}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log: classpath:/db/changelog/master.xml
  docker:
    compose:
      lifecycle-management: none
      enabled: false

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED}
    path: /api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}
    operationsSorter: alpha
    tagsSorter: alpha
    path: ${SWAGGER_PATH}
  show-actuator: true

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org:
      hibernate:
        type: ${LOGGING_LEVEL_HIBERNATE}
      springframework:
        web: ${LOGGING_LEVEL_SPRING}
  file:
    name: ./var/logs/app.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  logback:
    rollingpolicy:
      file-name-pattern: ./var/logs/app.%d{yyyy-MM-dd}.%i.log

cloudinary:
    cloud-name: ${CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

firebase:
  credentials:
    file: ${FIREBASE_CREDENTIALS_FILE}
  project-id: ${FIREBASE_PROJECT_ID}